name: MSPR_Pipeline

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: '21'
      - name: Build with Maven
        run: mvn -B package --file pom.xml # Probably add test here
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
              name: spotlight.jar
              path: ./target/spotlight-0.0.1-SNAPSHOT.jar
