name: Build and Push Docker Image

permissions: write-all
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: docker build -t ghcr.io/blambertt/spotlight/spotlight-api:latest .
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/blambertt/spotlight/spotlight-api:latest

  
  deploy-to-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger image to render.com
        run: https://api.render.com/deploy/srv-cpo3tceehbks738h42k0?key=jEPh2iUX4CY

      
